apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-pod
  template:
    metadata:
      labels:
        app: httpd-pod
    spec:
      containers:
      - image: httpd:latest
        name: httpd
        ports:
        - containerPort: 80
