apiVersion: v1
kind: Service
metadata:
  name: httpd-svc-nlb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  loadBalancerSourceRanges:
  - "192.168.0.0/16"
  - "100.64.0.0/16"
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app: httpd-pod
