apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deploy
spec:
  selector:
    matchLabels:
      app: kibana
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: my-kibana
        image: kibana:8.5.3
        ports:
        - containerPort: 5601
