apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      serviceAccountName: my-service-account
#      volumes:
#        - name: my-nginx-pvc
#          persistentVolumeClaim:
#            claimName: nginx-pvc
      containers:
      - name: my-app
        image: nginx:latest
        ports:
        - containerPort: 80
#        volumeMounts:
#          - name: my-nginx-pvc
#            mountPath: /etc/nginx
