apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-04cdfea9aad66bda9 
    fsType: ext4
