apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  #csi:
  #  driver: ebs.csi.aws.com
  #  fsType: ext4
  #  volumeHandle: vol-014cbeb706b086616
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-014cbeb706b086616
