apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-claim2
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: test-pv2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
