apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secrets-provider
spec:
  provider: aws
  secretObjects:
    - secretName: MySecret
      type: Opaque
      data:
        - objectName: "MySecret"
          key: username
  parameters:
    objects: |
      - objectName: arn:aws:secretsmanager:ap-southeast-1:221625973137:secret:MySecret-YYJM6r
        objectAlias: "MySecret"

