apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  nodeSelector:
    topology.kubernetes.io/zone: ap-southeast-1a
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: test-claim1
