kind: Pod
apiVersion: v1
metadata:
  name: secrets-store-inline
spec:
  serviceAccountName: nginx-deployment-sa 
  containers:
  - name: nginx-deployment
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "aws-provider" # Name of the secretProviderClass

