apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-provider
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: arn:aws:secretsmanager:ap-southeast-1:221625973137:secret:MySecret-YYJM6r
        jmesPath:
            - path: "username"
              objectAlias: "dbusername"
            - path: "password"
              objectAlias: "dbpassword"

